/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Heinrich (https://sketchfab.com/Gevalt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kuma-heavy-robot-r-9000s-8b77bdbe705f4e9697790fd404da49a9
Title: KUMA Heavy Robot R-9000S
*/

import {useRef} from 'react'
import {useGLTF, useAnimations} from '@react-three/drei'
import {useFrame} from "@react-three/fiber";

export function Model(props: any) {
    const group = useRef()
    const {nodes, materials, animations} = useGLTF('/src/assets/robot/kuma_heavy_robot_r-9000s.glb')
    const {actions} = useAnimations(animations, group)

    const meshRef = useRef();

    useFrame(() => {
        if (meshRef.current) {
            const skeleton = meshRef.current.skeleton;

            // Example: Rotate the third bone in y direction
            const bone = skeleton.bones[2]; // Change index for different bones
            bone.rotation.y += 0.01; // Rotate the bone over time
        }
    });

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="d08bcb9eee5d4ee7ba2cdda5726827dafbx" rotation={[Math.PI / 2, 0, 0]}>
                        <group name="Object_2">
                            <group name="RootNode">
                                <group
                                    name="Armature"
                                    position={[-866.654, 1714.409, 8.214]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                    scale={100}>
                                    <group name="Object_5">
                                        <primitive object={nodes._rootJoint}/>
                                        <skinnedMesh
                                            name="Object_19"
                                            geometry={nodes.Object_19.geometry}
                                            material={materials['Material.002']}
                                            skeleton={nodes.Object_19.skeleton}
                                            ref={meshRef}
                                        />
                                        <skinnedMesh
                                            name="Object_21"
                                            geometry={nodes.Object_21.geometry}
                                            material={materials['Material.001']}
                                            skeleton={nodes.Object_21.skeleton}
                                        />
                                        <group
                                            name="Object_18"
                                            position={[-34.199, -256.731, 114.388]}
                                            rotation={[-Math.PI / 2, 0, 0]}
                                            scale={100}
                                        />
                                        <group
                                            name="Object_20"
                                            position={[-34.199, -256.731, 114.388]}
                                            rotation={[-Math.PI / 2, 0, 0]}
                                            scale={100}
                                        />
                                    </group>
                                </group>
                                <group
                                    name="ArmLong037"
                                    position={[-34.199, -256.73, 114.388]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                    scale={100}
                                />
                                <group
                                    name="ArmLong000"
                                    position={[-34.199, -256.73, 114.388]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                    scale={100}
                                />
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}